######################## default configuration ####################
baseURL = "https://tobiaszpokorniecki.pl"
title = "Tobiasz Pokorniecki | Flutter developer | Full-stack Developer"
theme = "somrat"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # disable language from here
# google analutics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com


############################# Outputs ##############################
[outputs]
home = ["HTML"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"


#################### default parameters ################################
[params]
favicon = "images/favicon.png"
logo_light = "images/logo.png"
logo_dark = "images/logo-dark.png"
logo_width = "150px"
# Meta data
description = "Jestem absolwentem informatyki na Uniwersytecie Mikołaja Kopernika w Toruniu. Niedawno obroniłem tytuł inżyniera informatyki pracą opartą na uczeniu maszynowym oraz splotowych sieciach neuronowych. Obecnie staram się o tytuł magistra na tym samym uniwersytecie. Przez technikum i studia ciągnęły się za mną najróżniejsze języki programowania, jednak najbardziej zainteresowała mnie sfera WebApp i MobileApp developmentu. Swoją przygodę z aplikacjami zacząłem w 2019 roku tworząc, w oparciu o React.js, projekt zespołowy JudiBell, który zajął drugie miejsce w rankingu pod względem potencjału biznesowego. Obecnie rozwijam swoje umiejętności we Flutter oraz GoLang."
author = "Tobiasz Pokorniecki"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.
  
############################# social site ########################
[[params.social]]
icon = "fab fa-facebook-f"
link = "https://www.facebook.com/tobiasz.pokorniecki"

[[params.social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/lumizmatyk/"

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/radiol00"

[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/somratpro"


################################### Polish language #####################################
[Languages.en]
languageName = "PL"
languageCode = "pl"
contentDir = "content/polish"
weight = 1
home = "Strona Główna"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by somrat"


################# polish navigation ##################

# main menu
[[Languages.en.menu.main]]
name = "Strona Główna"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "O Mnie"
pre = "#"
url = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Umiejętności"
pre = "#"
url = "skills"
weight = 3

[[Languages.en.menu.main]]
name = "Portfolio"
pre = "#"
url = "portfolio"
weight = 4

[[Languages.en.menu.main]]
name = "Referencje"
pre = "#"
url = "testimonial"
weight = 5

[[Languages.en.menu.main]]
name = "Kontakt"
pre = "#"
url = "contact"
weight = 6